#name: CICD
#
#on:
#  push:
#    branches:
#      - master
#
#env:
#  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#
#jobs:
#  CD-dev:
#    name: Deploy to Fly.io develop
#    environment: beta
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - run: |
#          flyctl deploy --config fly.toml --remote-only -e DB_HOST=${{ secrets.DB_HOST }},\
#          a=87
#      - run: echo "Deploy to fly develop"


name: Linters

on:
  push:
    branches:
      - master
      - feature/test_ci_isort

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'

jobs:
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install package
        run: python -m pip install isort==5.11.4

      - name: Set changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.py
            **/*.py

      - name: Check isort
        run: |
          if [[ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]]; then
            echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs isort --check --diff &&
            echo "Isort was succeeded." ||
            exit 1
          else
            echo "0 Python files changed."
          fi

  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install package
        run: python -m pip install black==22.12.0

      - name: Set changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.py
            **/*.py

      - name: black
        run: |
          if [[ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]]; then
            echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs black --check --diff &&
            echo "Black was succeeded." ||
            exit 1
          else
            echo "0 Python files changed."
          fi

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install package
        run: python -m pip install pylint==2.15.5

      - name: Set changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.py
            **/*.py

      - name: pylint
        run: |
          if [[ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]]; then
            echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs pylint --rcfile .pylintrc &&
            echo "Pylint was succeeded." ||
            exit 1
          else
            echo "0 Python files changed."
          fi
