name: CICD

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  CD-dev:
    name: Deploy to Fly.io develop
    environment: beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.toml --remote-only -e DB_HOST=${{ secrets.DB_HOST }}, a=87
      - run: echo "Deploy to fly develop"